
language: cpp

common_sources: &all_sources
  - ubuntu-toolchain-r-test
  - llvm-toolchain-trusty

python:
  - 3.7

matrix:
  include:

    # - os: linux
    #   compiler: gcc
    #   sudo: require
    #   dist: xenial
    #   addons:
    #     apt:
    #       sources: *all_sources
    #       packages: 
    #         - g++-8
    #   env:
    #     - MATRIX_EVAL="export CC=gcc-8; export CXX=g++-8;"
    #   before_install: &update_cmake
    #     # Update compilers
    #     - eval "${MATRIX_EVAL}"
    #     - echo "CC=$CC CXX=$CXX"
    #     # Install a supported cmake version (>= 3.14)
    #     - wget -O cmake.sh https://cmake.org/files/v3.14/cmake-3.14.0-Linux-x86_64.sh 
    #     - sudo sh cmake.sh --skip-license --exclude-subdir --prefix=/usr/local
    #     - export PATH=/usr/local/bin:$PATH
    #     - cmake --version
    #   script:
    #     - python3 examples/run_all.py

    # - os: linux
    #   compiler: clang
    #   sudo: require
    #   dist: xenial
    #   addons:
    #       apt:
    #           sources: *all_sources
    #           packages:
    #             - g++-8
    #             - clang-6.0
    #   env:
    #     - MATRIX_EVAL="export CC=clang-6.0; export CXX=clang++-6.0;"
    #   before_install: *update_cmake
    #   script:
    #     - python3 examples/run_all.py


    - os: osx
      compiler: gcc
      addons:
        homebrew:
          packages:
          - gcc@8
          - cmake
          update: true
      before_install:
      script:
        - export PATH="$(brew --prefix)/bin:$(brew --prefix)/sbin:$PATH"
        - export CC=gcc-8; export CXX=g++-8;
        - echo "$(CXX) --version"
        - python3 examples/run_all.py

    - os: windows
      before_install:
        - choco install python3
        - choco upgrade cmake
        - export PATH="/c/Python37:/c/Python37/Scripts:$PATH"
        - python -m pip install --upgrade pip wheel
      script:
        - python examples/run_all.py


 